[package]
name = "pminimal"
authors = ["Christoph Jabs <christoph.jabs@helsinki.fi>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsat = { path = "../rustsat", default-features = false, features = ["default-but-solvers", "multiopt"] }
maxpre = { path = "../maxpre-rs", optional = true, features = ["multiopt"] }
cpu-time = { optional = true, version = "1.0.0" }
clap = { optional = true, version = "4.2.4", features = ["derive", "cargo"] }
concolor-clap = { optional = true, version = "0.1.0" }
termcolor = { optional = true, version = "1.2.0" }
atty = { optional = true, version = "0.2.14" }
signal-hook = { optional = true, version = "0.3.15" }

[features]
default = ["cadical", "build-binary"]
cadical = ["rustsat/cadical"]
build-binary = [
  "dep:clap",
  "dep:concolor-clap",
  "dep:termcolor",
  "dep:atty",
  "dep:cpu-time",
  "dep:maxpre",
  "dep:signal-hook",
  "rustsat/compression",
]

[profile.release]
lto = true
