[package]
name = "pminimal"
author = "Christoph Jabs <christoph.jabs@helsinki.fi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsat = { path = "../rustsat", default-feature = false, features = ["multiopt"] }
clap = { optional = true, version = "4.0", features = ["derive"] }
concolor-clap = { optional = true, version = "0.0.12" }
termcolor = { optional = true, version = "1.1" }
atty = { optional = true, version = "0.2" }

[features]
default = ["cadical", "build-binary"]
cadical = ["rustsat/cadical"]
build-binary = ["dep:clap", "dep:concolor-clap", "dep:termcolor", "dep:atty", "rustsat/compression"]