[package]
name = "scuttle"
authors = ["Christoph Jabs <christoph.jabs@helsinki.fi>"]
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A multi-objective MaxSAT solver."
keyworks = ["solver", "multi-objective optimization", "maxsat"]
repository = "https://github.com/chrjabs/scuttle"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsat = { version = "0.2", path = "../rustsat/rustsat", features = ["multiopt"] }
rustsat-cadical = { optional = true, version = "0.1", path = "../rustsat/cadical", features = ["v1-7-1"] }
maxpre = { version = "0.2", path = "../maxpre-rs", optional = true, features = ["multiopt"] }
cpu-time = { optional = true, version = "1.0.0" }
clap = { optional = true, version = "4.2.4", features = ["derive", "cargo"] }
concolor-clap = { optional = true, version = "0.1.0" }
termcolor = { optional = true, version = "1.2.0" }
atty = { optional = true, version = "0.2.14" }
signal-hook = { optional = true, version = "0.3.15" }
scuttle_derive = { path = "./derive" }

[build-dependencies]
rustsat-cadical = { version = "0.1", path = "../rustsat/cadical", features = ["v1-7-1"] }

[features]
default = ["build-binary", "phasing", "sol-tightening"]
oracle-term = ["scuttle_derive/oracle-term"]
phasing = ["scuttle_derive/phasing"]
sol-tightening = ["scuttle_derive/sol-tightening"]
build-binary = [
  "dep:clap",
  "dep:concolor-clap",
  "dep:termcolor",
  "dep:atty",
  "dep:cpu-time",
  "dep:maxpre",
  "dep:signal-hook",
  "dep:rustsat-cadical",
  "rustsat/compression",
]

[profile.release]
lto = true
